export const SET_LOGINED = 'SET_LOGINED'

export const REMOVE_LOGINED = 'REMOVE_LOGINED'

export const SET_USER = 'SET_USER'

export const ADD_READED_MESSAGE = 'ADD_READED_MESSAGE'

export const REMOVE_UNREAD_MESSAGE = 'REMOVE_UNREAD_MESSAGE'

export const ADD_UNREAD_MESSAGE = 'ADD_UNREAD_MESSAGE'

export const SET_USER_PERMISSIONS = 'SET_USER_PERMISSIONS'

export const SET_REFERSH_OPTION = 'SET_REFERSH_OPTION'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_TOKEN = 'SET_TOKEN'

export const SET_USER_ID = 'SET_USER_ID'

export const REGISTER_BASIC = 'REGISTER_BASIC'

export const REGISTER_EDU = 'REGISTER_EDU'

export const REGISTER_EXPECTED_POSITION = 'REGISTER_EXPECTED_POSITION'

export const REGISTER_LAST_EXPERIENCE = 'REGISTER_LAST_EXPERIENCE'

export const LOGINOUT = 'LOGINOUT'

export const SET_OXTITLE = 'SET_OXTITLE'

export const SET_NOW_CITY = 'SET_NOW_CITY'

export const SET_USER_MOBILE = 'SET_USER_MOBILE'

export const SET_NOW_PROVINCE = 'SET_NOW_PROVINCE'

export const CLEAR_REGISTER_DATA = 'CLEAR_REGISTER_DATA'
